baseURL = "https://jmhreif.com/"
languageCode = "en-us"
title = "Jennifer Reif"
theme = ["ananke"]

Paginate = 9

[params]
description = """
    Java Developer Advocate at Neo4j, conference speaker, blogger, avid developer, and problem-solver.
    """
github = "https://github.com/JMHReif"
twitter = "https://twitter.com/JMHReif"
linkedin = "https://www.linkedin.com/in/jmhreif/"
rss = "https://jmhreif.com/index.xml"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-green"
featured_image = "/img/neo4j-london-2018.jpg"
show_reading_time = true
custom_css = ["custom.css"]

[[params.ananke_socials]]
name = "podcast"
url = "https://jmhreif.podbean.com/"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Abstracts"
  identifier = "abstracts"
  weight = 400
  url = "/abstracts/"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']